[package]
name = "simple-mqtt-desktop-bridge"
version = "1.0.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
log = "0.4.22"
notify-rust = "4.11.3"
rumqttc = "0.24.0"
serde = "1.0.210"
serde_json = "1.0.128"
sysinfo = "0.32.0"
